### ISSUE TITLE
Cpp1st - Select 2nd topic

### ISSUE THREAD

**Issue by hmlearning** [th4inquiry/PentaDevs#15]
Congrats! You succesfully finished your task.
Please select next round topic.

**Comment by BMPark-Lab** [comment]
my pick is "exception and error handling"

**Comment by astrophenomenon** [comment]
My pick is "l-value, r-value, copy, move"

**Comment by hmlearning** [comment]
all we did it.

87340e60092d3d3bbe1c667d16b30fd34be07ed4
